### ISSUE TITLE
Error in running test script

### ISSUE THREAD

**Issue by BehzadBozorgtabar** [Raymond-sci/AND#4]
When I run the test script pointing to the checkpoints, I am getting size mismatch error in below:

RuntimeError: Error(s) in loading state_dict for ANsDiscovery:
	size mismatch for instance_indexes: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([50000]).
	size mismatch for neighbours: copying a param with shape torch.Size([50000, 1]) from checkpoint, the shape in current model is torch.Size([0]).
	size mismatch for anchor_indexes: copying a param with shape torch.Size([50000]) from checkpoint, the shape in current model is torch.Size([0]).

Any suggestion?

**Comment by Raymond-sci** [comment]
This should be caused by the inconsistency of the variable's shape in the saved `ANsDiscovery` instance and the initialised one, thanks for pointing that out. 

I will manage time to fix this bug but not sure when it can be done. One possible workaround is to save and load the entire `ANsDiscovery` and `NonParametricClassifier` instances instead of their state_dict:

```python
# saving
torch.save({..., 'ANs_discovery' : ANs_discovery, 'npc' : npc, ...}, path_to_save)

# loading
ckpt = torch.load(path_to_load)
ANs_discovery = ckpt['Ans_discovery']
npc = ckpt['npc']
```

**Comment by BehzadBozorgtabar** [comment]
Thanks for quick reply @Raymond-sci

It seems there are two functions for saving state-dict, one in the main function and the other one is in lib/utils.py, Line 50.  I will try to save and load as you suggested.

**Comment by BehzadBozorgtabar** [comment]
Thanks for quick reply @Raymond-sci

It seems there are two functions for saving state-dict, one in the main function and the other one is in lib/utils.py, Line 50. I just try your suggestion and it still does not work.

**Comment by BehzadBozorgtabar** [comment]
I just followed your suggestion and saved directly using torch.save() instead of whole as a state dict, but I've got another error:

File "/media/bozorgta/Elements/AND/AND/lib/protocols.py", line 62, in kNN
    trainFeatures = npc.memory
AttributeError: 'OrderedDict' object has no attribute 'memory'

**Comment by Raymond-sci** [comment]
Could you please paste the snippet that you used to load and save checkpoint file?
or you can also try this, it works for me:

```

```

**Comment by Raymond-sci** [comment]
you may like to try this, it works for me:

For loading, replace L113 - L114 by
```python
npc = ckpt['npc']
ANs_discovery = ckpt['ANs_discovery']
```

For saving, replace L185 - L186 by
``` python
'ANs_discovery' : ANs_discovery,
'npc' : npc,
```
